name: Comment with HTML on Commit

on:
  push:
    branches:
      - main  # Adjust this if you want to target a different branch

jobs:
  generate-and-comment:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the HTML file
      # Replace this with the actual command to generate your HTML
      - name: Generate HTML
        run: |
          echo '<html><body><h1>Hello, World!</h1></body></html>' > output.html

      # Read the generated HTML content
      - name: Read HTML Content
        id: read_html
        run: |
          html_content=$(cat output.html)
          echo "::set-output name=html_content::$html_content"

      # Add a comment to the commit
      - name: Comment on Commit
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-id: ${{ github.sha }}
          body: |
            <details>
              <summary>Generated HTML</summary>
              <pre>
              ${{ steps.read_html.outputs.html_content }}
              </pre>
            </details>

