name: Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    log:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: echo "Continuous Deployment!"
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up database
              run: |
                  chmod +x ./setup-db.bash
                  ./setup-db.bash

            - name: Cache yarn dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                      .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn install

            - name: Run CI tasks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn ci

            - name: Set Git user name
              run: git config --global user.name "Fernando Hurtado"

            - name: Set Git user email
              run: git config --global user.email "fernandohur@gmail.com"

            - name: Publish package to NPM
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn pub
