name: Continuous Deployment

on:
    push:
        branches-ignore: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up database
              run: |
                  chmod +x ./setup-db.bash
                  ./setup-db.bash

            - name: Cache yarn dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      **/node_modules
                      .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn install

            - name: Run CI tasks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn ci

            - name: Set Git user name
              run: git config user.name "github-actions[bot]"

            - name: Set Git user email
              run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: See refs
              run: git branch -b

            - name: Fetch refs
              run: git fetch

            - name: Checkout to master
              run: git checkout master

            # - name: Set Git remote URL
            #   run: git remote add origin ${{ github.repositoryUrl }}

            - name: Publish package to NPM
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn publish-minor-versions
