name: Continuous Integration

on:
    pull_request:
        branches: [master]

jobs:
    ci:
        name: Run CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: yarn

            - name: Set up database
              run: |
                  chmod +x ./setup-db.bash
                  ./setup-db.bash

            - name: Cache yarn dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      **/node_modules
                      .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn install

            - name: Run CI tasks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn ci
